name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Load environment variables from file
        run: |
          while IFS= read -r line; do
            if [[ ! $line =~ ^# ]]; then
              export_key="$(echo $line | cut -d ':' -f 1)"
              export_value="$(echo $line | cut -d ':' -f 2- | xargs)"
              echo "$export_key=$export_value" >> $GITHUB_ENV
            fi
          done < .github/workflows/config/env.yml

      - name: Display Environment Variables
        run: |
          echo "PROJECT_ID=${{ env.PROJECT_ID }}"
          echo "SERVICE_NAME=${{ env.SERVICE_NAME }}"
          echo "IMAGE=${{ env.IMAGE }}"
          echo "REGION=${{ env.REGION }}"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Create Artifact Registry repository if not exists
        run: |
          gcloud artifacts repositories create ex-ea-email-repo \
            --repository-format=docker \
            --location=europe-west2 \
            --description="Repository for Every Action Email Service" \
            --quiet || true

      - name: Configure Docker
        run: gcloud auth configure-docker europe-west2-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker build -t europe-west2-docker.pkg.dev/${{ env.PROJECT_ID }}/ex-ea-email-repo/${{ env.SERVICE_NAME }}:${{ github.sha }} .
          docker push europe-west2-docker.pkg.dev/${{ env.PROJECT_ID }}/ex-ea-email-repo/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image europe-west2-docker.pkg.dev/${{ env.PROJECT_ID }}/ex-ea-email-repo/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            --platform managed \
            --region europe-west2 \
            --allow-unauthenticated

      - name: Verify Deployment
        run: |
          # Wait for service to be ready
          sleep 30
          
          # Get service URL
          SERVICE_URL=$(gcloud run services describe ${{ env.SERVICE_NAME }} \
            --platform managed \
            --region europe-west2 \
            --format 'value(status.url)')
          
          # Check if service is responding
          curl -f $SERVICE_URL/health || exit 1
